// <auto-generated />
using ExampleWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExampleWebAPI.Data.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20220415141053_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.4");

            modelBuilder.Entity("ExampleWebAPI.Data.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Published")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Seeded content for post 1.",
                            Published = true,
                            Title = "Post 1"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Seeded content for post 2.",
                            Published = true,
                            Title = "Post 2"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Seeded content for post 3.",
                            Published = true,
                            Title = "Post 3"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Seeded content for post 4.",
                            Published = true,
                            Title = "Post 4"
                        },
                        new
                        {
                            Id = 5,
                            Content = "Seeded content for post 5.",
                            Published = true,
                            Title = "Post 5"
                        },
                        new
                        {
                            Id = 6,
                            Content = "Seeded content for post 6.",
                            Published = true,
                            Title = "Post 6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
